
version: '3.6'
services:

  # App Backend PostgreSQL
  postgres:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: jdbc:postgresql://postgres:5432/jobsdb
      POSTGRES_DB: jobsdb
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

#  # App Backend
#  job-board:
#    build: ./
#    volumes:
#      - ./:/usr/src/job-board
#    command: sbt run
#    working_dir: /usr/src/job-board
#    ports:
#      - "8080:8080"
#    environment:
#      POSTGRES_URI: jdbc:postgresql://postgres:5432/jobsdb
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#      POSTGRES_URL: jdbc:postgresql://postgres:5432/jobsdb
#      POSTGRES_DB: jobsdb
#      POSTGRES_HOST: postgres
#    depends_on:
#      - postgres